title: Products
sites:
  - default
  - english
  - deutsch
propagate: false
template: products/show
layout: layout
revisions: false
route: '/products/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 1
